spring:
  application:
    name: GestionAvis

  data:
    mongodb:
      username: sa
      password: MotDePasse123!
      host: localhost
      port: 27017
      database: Gestion_Avis
      authentication-database: admin

  logging:
    level:
      org:
        springframework:
          mongodb:
            core:
              MongoTemplate: DEBUG